name: Release

on:
  push:
    branches: [main]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
    
      - name: Exist if it's not a solution branch
        run: |
           if [[ ! ${{ github.ref_name }} =~ [0-9]+-* ]]; then
             echo "The branch name doesn't follow a solution branch name format"
             exit 1
           else 
            id="TEST"
            echo "::set-output name=id::$id"
           fi
      - name: create env variable
        run: |
          string="test"
          cat ${{ secrets[steps.vars.outputs.id] }} >> ~/.tfvars
            
      - name: Checkout
        uses: actions/checkout@v3
